### ISSUE TITLE
Parsing fails on "params: []"

### ISSUE THREAD

**Issue by professor** [ryanmoran/piper#20]
concourse can parse a task yml file with `params: []`, however, piper complains with `  line 10: cannot unmarshal !!seq into map[string]string`

Here's a sample task file....

```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/bump-stemcell.sh

params: []

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: stemcell
outputs:
  - name: git-kubo-deployment-output
```
