### ISSUE TITLE
image_resource is not supported

### ISSUE THREAD

**Issue by DennisDenuto** [ryanmoran/piper#3]
piper does not use docker image name from image_resource (expects image instead)

task.yml:

```
image_resource:
  type: docker-image
  source:
    repository: repo/docker-image-name
```

Results in: 

```
Using default tag: latest
repository name must have at least one component
2016/05/26 17:19:52 exit status 1
```

We've worked around this by temporarily adding an `image:` key with the value from `image_resource.source.repository`, but it would be nice if we didn't have to do this.
